apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Values.bpschartversion }} 
    release: {{ .Values.bpsrelease }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app:  {{ .Values.service.name }}
  type: {{ .Values.service.type }}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service.name }} 
  name: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app:  {{ .Values.service.name }} 
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        name: {{ .Values.service.name }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.deployment.configMap }}
