apiVersion: v1
name: bpstest-orderdemo-db2
description: IBM Db2 Developer-C Edition 11.1.2.2 iFix002
version: 1.1.1
keywords:
- db2
- database
- sql
home: https://www.ibm.com/analytics/us/en/db2/
icon: https://na.cumulusrepo.com/assetswithkey/ba5345023eb40c21d01ad81bc927a36f/db2logoicp-01.png/v1
maintainers:
  - name: IBM Analytics
sources:
  - https://github.com/IBM/charts/tree/master/stable
tillerVersion: ">=2.4.0"
engine: gotpl
