apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bpsGlobals.db2pwsecretsName }}
  labels:
    app: {{ .Values.service.name}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Values.bpsGlobals.releaseName }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.db2inst.password }}
  password:  {{ .Values.db2inst.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
