apiVersion: v1
kind: Service
metadata:
  name: {{.Values.bpsGlobals.serviceName }}
  labels:
    app: {{ .Values.bpsGlobals.serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{  .Values.bpsGlobals.releaseName }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }} 
    targetPort: 50000
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: {{ .Values.service.tsport }}
    targetPort: 55000
    protocol: TCP
    name: {{ .Values.service.name }}-text
  selector:
    app: {{ .Values.bpsGlobals.serviceName }}
