apiVersion: v1
description: Elasticsearch stats exporter for Prometheus
name: ibm-elasticsearch-exporter
version: 0.2.2
appVersion: 1.0.2
home: https://github.com/justwatchcom/elasticsearch_exporter
sources:
  - https://github.com/justwatchcom/elasticsearch_exporter
keywords:
  - metrics
  - elasticsearch
  - monitoring
  - adapter
  - Limited
  - ppc64le
  - Tools
  - ICP
maintainers:
  - name: IBM ISV Team
    email: smohite@us.ibm.com
tillerVersion: '>=2.7.2'
