apiVersion: v1
kind: Service
metadata:
  name: {{ template "jetty.fullname" . }}
  labels:
    app: {{ template "jetty.name" . }}
    chart: {{ template "jetty.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port.port1 }}
      targetPort: http
      name: http
    - port: {{ .Values.port.port2 }}
      targetPort: http1
      name: http1

  selector:
    app: {{ template "jetty.name" . }}
    release: {{ .Release.Name }}
